site_name: oceansprint.org
site_description: "A week of Nix hacking near the ocean"
site_url: "https://oceansprint.org"
repo_name: "oceansprint/oceansprint.org"
repo_url: "https://github.com/oceansprint/oceansprint.org"
edit_uri: "edit/main/docs"
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: white
    accent: "#FBFBFB"
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - toc.integrate
nav:
  - Home: index.md
  - Accomodation: accomodation.md
  - Schedule: schedule.md
  - Activities: activities.md
  - Restaurants: restaurants.md
  - Reports:
      - OceanSprint 2025: reports/2025.md
      - OceanSprint 2023: reports/2023.md
      - OceanSprint 2022/November: reports/2022-november.md
      - OceanSprint 2022/April: reports/2022-april.md
      - OceanSprint 2021: reports/2021.md
  - Past events:
      - OceanSprint 2023: past-events/2023.md
      - OceanSprint 2022/November: past-events/2022-november.md
      - OceanSprint 2022/April: past-events/2022-april.md
      - OceanSprint 2021: past-events/2021.md
copyright: Copyright &copy; 2021 - 2024 <a href="https://niteo.co/">Niteo</a> & <a href="https://cachix.org">Cachix</a>
plugins:
  blog: {}
  social:
    cards_layout_options:
      background_color: "#FBFBFB"
      color: "#425C82"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oceansprint/oceansprint.org
  generator: false
markdown_extensions:
  - tables
  - admonition
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
